/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.BanHang;

import SQL.connect;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author hatro
 */
public class jpBanHang extends javax.swing.JPanel {

    public JPanel jp ;
    /**
     * Creates new form jpBanHang
     */
    public jpBanHang() {
        initComponents();
        fillTable();
    }
            
    private void fillTable(){
        connect conn = new connect("root", "","ql_cafe");
        conn.getConnect();
        ResultSet rs = conn.getData("banan");
        int cow = 0;
        try {
            while (rs.next()) {                
                cow++;
            }
        } catch (Exception e) {
            System.out.println("khong lay dc so ban ghi !");
        }
        JButton[] btn = new JButton[cow];
        jpBan.removeAll();
        for (int i = 0; i < cow; i++) {
            btn[i] = new JButton();
            btn[i].setName("ban");
            btn[i].setText("Bàn " + i);
            btn[i].setPreferredSize(new Dimension(90, 70));
            btn[i].setBackground(Color.decode("#8080ff"));
            btn[i].setActionCommand(btn[i].getText());
            btn[i].addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    //btn[i].getText();
                    System.out.println("act:" + evt.getActionCommand());
                    jp = new jpStatusTb();
                    JpDetail.removeAll();
                    JpDetail.add(jp);
                    JpDetail.updateUI();
                    System.out.println("da an vao day");
                }
            });
            jpBan.add(btn[i]);
        }
        jpBan.validate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpTable = new javax.swing.JPanel();
        jpBan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JpDetail = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JpTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jpBan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Danh sách các bàn");

        javax.swing.GroupLayout JpTableLayout = new javax.swing.GroupLayout(JpTable);
        JpTable.setLayout(JpTableLayout);
        JpTableLayout.setHorizontalGroup(
            JpTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jpBan, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpTableLayout.setVerticalGroup(
            JpTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpTableLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBan, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        JpDetail.setBackground(new java.awt.Color(182, 103, 7));
        JpDetail.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpDetail;
    private javax.swing.JPanel JpTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpBan;
    // End of variables declaration//GEN-END:variables
}
