/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.QuanLy;

import Models.Loai;
import Models.Mon;
import SQL.connect;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hatro
 */
public class jpThucDon extends javax.swing.JPanel {

    Vector header = new Vector();
    Vector data = new Vector();
    Vector header1 = new Vector();
    Vector data1 = new Vector();
    /**
     * Creates new form jpThucDon
     */
    public jpThucDon() {
        initComponents();
        header.add("Mã món");
        header.add("Tên món");
        header.add("Đơn giá");
        header.add("Đơn vị tính");
        header1.add("Mã loại");
        header1.add("Tên loại");
        DefaultTableModel model = (DefaultTableModel) tbMon.getModel();
        DefaultTableModel model1 = (DefaultTableModel) tbLoai.getModel();
        model.setDataVector(data, header);
        model1.setDataVector(data1, header1);
        show();
    }

    public void show(){
        connect conn = new connect("root", "", "ql_cafe");
        conn.getConnect();
        ArrayList<Mon> arr = conn.getMon("");
        ArrayList<Loai> arr1 = conn.getLoai();
        if (arr!=null) {
            for (int i = 0; i < arr.size(); i++) {
                Vector row = new Vector();
                row.add(arr.get(i).getIdnhom());
                row.add(arr.get(i).getName());
                row.add(arr.get(i).getDongia());
                row.add(arr.get(i).getLoai());
                data.add(row);
            }
        }
        if (arr1!=null) {
            for (int i = 0; i < arr1.size(); i++) {
                Vector row1 = new Vector();
                row1.add(arr1.get(i).getMa());
                row1.add(arr1.get(i).getNameLoai());
                data1.add(row1);
            }
        }
        DefaultTableModel model = (DefaultTableModel) tbMon.getModel();
        DefaultTableModel model1 = (DefaultTableModel) tbLoai.getModel();
        model.setDataVector(data, header);
        model1.setDataVector(data1, header1);
        data = new Vector();
        data1 = new Vector();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbMon = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLoai = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        tbMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã món", "Loại món", "Tên món", "Đơn giá", "Đơn vị tính "
            }
        ));
        jScrollPane1.setViewportView(tbMon);

        jLabel1.setText("Danh sách các món");

        tbLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã loại", "Tên loại món"
            }
        ));
        jScrollPane2.setViewportView(tbLoai);

        jLabel2.setText("Các loại món");

        jButton1.setText("Thêm món");

        jButton2.setText("Xoá món");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sửa món");

        jButton4.setText("Thêm loại");

        jButton5.setText("Xoá loại");

        jButton6.setText("Sửa loại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(318, 318, 318))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton5)
                        .addComponent(jButton4)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:\
        
        if (tbMon.getSelectedRow() != -1) {
            int row = tbMon.getSelectedRow();
            String name = (String) tbMon.getValueAt(row, 1);
            System.out.println(name);
            int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xoá");
            if (x == 0 ) {
                connect con = new connect("root", "", "ql_cafe");
                con.getConnect();
                boolean c = con.deleteMon(name);
                show();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Chưa chọn mục cần xoá");
        }
        show();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbLoai;
    private javax.swing.JTable tbMon;
    // End of variables declaration//GEN-END:variables
}
